name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # Every 6 hours
    - cron: "0 */6 * * *"
  # This command allows us to run the Action manually from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out the repository so that the job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      # Generates the snake
      - name: Generate the snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ashvinck
          # These next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Displays the status of the build. Makes it easier for debugging (if there are any issues).
      - name: Show build status
        run: git status

      # Pushes the changes to the main branch
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true

      # Deploys the generated files to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # Specifies the output branch we mentioned above
          target_branch: output
          # Specifies the build directory where the generated files are located
          build_dir: dist
        env:
          # Passes the GitHub token for authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
